### ISSUE TITLE
EIP-155

### ISSUE THREAD

**Issue by marcoVanLarco** [AlphaWallet/Web3E#14]
Hello, thanks for this. This works with Goerli, but not with Sepolia which requires functions to be signed according to EIP-155. Do you have any plans to update? Thank you.

**Comment by tomasz90** [comment]
@marcoVanLarco I added PR about it, you can get changes from it :)

**Comment by JamesSmartCell** [comment]
@tomasz90 thankyou for the outstanding PR! I have merged and also expanded it slightly to work with chains with a larger chainId like Sepolia. I think we can close this now.
