### ISSUE TITLE
conversion from 'uint256_t' to 'size_t' {aka 'unsigned int'} is ambiguous

### ISSUE THREAD

**Issue by lyhistory** [AlphaWallet/Web3E#18]
Web3.cpp compile error:
`string Web3::getString(const string *json)
{
    TagReader reader;
    string parseVal = reader.getTag(json, "result");
    vector<string> *v = Util::ConvertStringHexToABIArray(&parseVal);
    
    uint256_t length = uint256_t(v->at(1));
    int lengthIndex = (size_t)length;`

![image](https://github.com/AlphaWallet/Web3E/assets/1522513/a80c54ea-af06-4006-a4bf-a7e3b231707e)

**Comment by JamesSmartCell** [comment]
Got it, thanks for reporting. I have fixed this and will do a new release today.

**Comment by JamesSmartCell** [comment]
Fixed in v1.44
